"""initial tables

Revision ID: 408e3abbab89
Revises: 
Create Date: 2026-02-02 01:57:06.994697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408e3abbab89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recycling_certificates',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('pickup_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('recycler_id', sa.String(length=36), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('co2_saved', sa.Float(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'COLLECTOR', 'RECYCLER'), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('collector_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED'), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('total_pickups', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('pickup_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('collector_id', sa.String(length=36), nullable=True),
    sa.Column('recycler_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'ASSIGNED', 'EN_ROUTE', 'COLLECTED', 'HANDED_TO_RECYCLER', 'PROCESSING', 'RECYCLED', 'CANCELLED'), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('time_slot', sa.String(length=50), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('priority', sa.Enum('NORMAL', 'URGENT'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recycler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recycler_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('facility_name', sa.String(length=200), nullable=True),
    sa.Column('certification', sa.String(length=100), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED'), nullable=True),
    sa.Column('total_processed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ewaste_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pickup_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('estimated_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickup_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pickup_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickup_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('ewaste_items')
    op.drop_table('recycler_profiles')
    op.drop_table('pickup_requests')
    op.drop_table('collector_profiles')
    op.drop_table('users')
    op.drop_table('recycling_certificates')
    # ### end Alembic commands ###
